### ISSUE TITLE
ftree search states: "15928 Results found for tel;prefix" when using "Starts with"

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-front#10]
When searching ftrees with "starts with" or "sounds like" the results returned are stated to belong to "tel;prefix" and "Shimon;phonetic" respectively.

http://prntscr.com/b7er9n

**Comment by nuritgazit** [comment]
@TheGrandVizier please re-test

**Comment by TheGrandVizier** [comment]
Valid

**Comment by Inna-r** [comment]
@TheGrandVizier   please translate  'x Results found for your query"

**Comment by TheGrandVizier** [comment]
נמצאו 0 תוצאות עבור החיפוש שלכם
