### ISSUE TITLE
Missing data icon displayed even when data is not missing (bad date format?)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#100]
We display icons for missing data even when the data is not missing.
This is likely because we cannot understand a lot of the dates formats the users elect to use when providing information on individuals.
This would require some sort of converter that changes all dates into a standardized format.

**Comment by daonb** [comment]
#54

**Comment by TheGrandVizier** [comment]
This is best served by waiting for clearmesh, to be honest.
