### ISSUE TITLE
Case where trees do not display information that we do have.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#102]
In this tree:
http://test.dbs.bh.org.il/person/1729/I256
the name of the individual is blank.
When the user hovers the mouse over the blank name, a tooltip appears with a name (in this case, a letter).

Repro:
1. Arrive at link
2. Focus on guy with no name
3. Hover over lack of name.

**Comment by daonb** [comment]
#54
