### ISSUE TITLE
Luminaries (personalities) are displayed under the "images and videos" results tab. Again.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#103]
Luminaries results in general search are presented under the images and videos tab.

Repro:
1. Go to gen search
2. Search for "Lo"
3. Go to Images and Videos tab.
Result:
Some persons are displayed under the images and videos tab.

**Comment by daonb** [comment]
Need to get an elastic search expert. @MeirKriheli can you help?

**Comment by Inna-r** [comment]
#54
