### ISSUE TITLE
Need better way to navigate in recently viewed.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#112]
Currently navigating in the "recently viewed" section is very hard as each click moves the strip one item forward or back. In order to go all the way back to the beginning, up to 35 clicks can be required.

**Comment by TheGrandVizier** [comment]
I suggest a double arrow on each side to scroll all the way back or forward.

**Comment by daonb** [comment]
Makes sense. @Netush can you design the button?

**Comment by Netush** [comment]
I suggest that we just change the behavior of the button, instead of moving one item - it will move 12 item - so the user will see the last thing on the strip but the rest of strip will change.
