### ISSUE TITLE
Allow user to login through facebook|google|twitter

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-front#119]
Instead of entering an email, the user will click a button and will authorize our facebook app to get some basic information and email address.

**Comment by TheGrandVizier** [comment]
Why not go all the way and allow google + also? :dancer:

**Comment by daonb** [comment]
and twitter, we should have all three.

**Comment by nuritgazit** [comment]
@TheGrandVizier this is also a backend issue

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/dbs-back#36
