### ISSUE TITLE
Autocomplete for fields in /person

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#123]
Currently, we have no autocomplete for ftree search.
This will help greatly with first and last names.

**Comment by daonb** [comment]
Need to add API Endpoints for person/places, persons/first_names, persons/family_names to return a list of possibles found in the tree

**Comment by nuritgazit** [comment]
We are waiting for ClearMash to do this for us

**Comment by TheGrandVizier** [comment]
This whole issue is irrelevant as searches are being merged.
