### ISSUE TITLE
some item's content isn't displayed in Hebrew 

### ISSUE THREAD

**Issue by Inna-r** [Beit-Hatfutsot/dbs-front#128]
In this [example] (http://dbs.bh.org.il/he/%D7%A0%D7%95%D7%A3-%D7%94%D7%99%D7%95%D7%93%D7%9F-%D7%A1%D7%95%D7%95%D7%90%D7%A0%D7%94-%D7%A1%D7%95%D7%A8%D7%99%D7%A0%D7%90%D7%9D-%D7%A6%D7%99%D7%95%D7%A8-%D7%9E%D7%99%D7%9D-1839/%D7%AA%D7%9E%D7%95%D7%A0%D7%94), the api returns description in Hebrew UTF8 encoded

**Comment by TheGrandVizier** [comment]
Now if you go to http://test.dbs.bh.org.il/he/%D7%A0%D7%95%D7%A3-%D7%94%D7%99%D7%95%D7%93%D7%9F-%D7%A1%D7%95%D7%95%D7%90%D7%A0%D7%94-%D7%A1%D7%95%D7%A8%D7%99%D7%A0%D7%90%D7%9D-%D7%A6%D7%99%D7%95%D7%A8-%D7%9E%D7%99%D7%9D-1839/%D7%AA%D7%9E%D7%95%D7%A0%D7%94

You get an infinite loading screen and no data at all.

**Comment by TheGrandVizier** [comment]
Still cannot be displayed in hebrew in anything but chrome.
