### ISSUE TITLE
Add Photo Unit Number to all images in the item page

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#13]
Design is here: https://projects.invisionapp.com/d/#/console/904587/107843832/preview

**Comment by daonb** [comment]
The DB has all kind of numbers and we're not sure what is the correct one. @Netush  Can you please reply with an example - a link to a photo on the site and the number you'd like to see?

**Comment by nuritgazit** [comment]
We need to Photo unit.
In this case, for example: http://dbs.bh.org.il/image/view-of-the-joden-savanne-surinam-water-color-1839
the photo unit ID is 10013

**Comment by Netush** [comment]
I attached the English and Hebrew Sketch
![itempage-text_cretivecommons-heb](https://cloud.githubusercontent.com/assets/19781656/16298812/df30bc46-393f-11e6-91fe-e746a1f2629a.jpg)
![itempage-text_cretivecommons-eng](https://cloud.githubusercontent.com/assets/19781656/16298813/df33ead8-393f-11e6-9bf3-a56522ecd268.jpg)
