### ISSUE TITLE
Individual with no last name is reflected in the browsers tab name.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#133]
When an individual in a tree has no last name, this is reflected in the tab name of the browser.
It causes ugliness such as this:

http://prntscr.com/bm4cat

The missing data is filled in for with the word UNKNOWN in capitals.

**Comment by TheGrandVizier** [comment]
More information:
In contrast, a few steps below, in the same tree, we have a Chaim that has no last name, yet the tab is named with the last name of his parent:
http://prntscr.com/bm4e69

**Comment by daonb** [comment]
the word UNKNOWN is there because that's the last name of the person in the tree, as to Chaim page, the problem was with the information displayed in the center box and it's now fixed - http://test.dbs.bh.org.il/person/655/I2296
