### ISSUE TITLE
Error message does not time out when user is taken to ftree search from Wizard.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#134]
When a user is taken to the ftree search as a result of a failure of the wizard,
The error message belonging to the wizards failed search remains on screen until it is clicked.

There are two issues here.
1. It belongs to the wizard, but we are not on the wizard page any more. The ftrees shows results, so this creates confusion. Are there results or are there not?

2. It should time out like any other error message of this type.

**Comment by Inna-r** [comment]
fixed by #98
