### ISSUE TITLE
Notification for items that only exist in one language

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#14]
Design is here: https://projects.invisionapp.com/d/#/console/904587/126924451/preview

**Comment by TheGrandVizier** [comment]
Can we prioritize this a bit higher?
Searching of Abraham in general search provides about 30% empty result cards due to lack of a text in the required language.
Mostly its the hebrew texts that are missing.

@nuritgazit

**Comment by TheGrandVizier** [comment]
Also, there is no handeling of the empty cards in the link you provided, as far as I can tell.
The item page itself is one thing, but the results cards shoulnt be blank in the resutls screen.

**Comment by TheGrandVizier** [comment]
This needs a a small discussion and design.

**Comment by Netush** [comment]
There's a new sketch (same link)
