### ISSUE TITLE
Remove "Exit tree" button, shift assets into it's position.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#140]
The "Exit" tree button is not needed at the moment and should be removed in favor of saving space.
In the future we can replace it with a button that toggles mini-maxi views for mobiles but for now it can go.

**Comment by TheGrandVizier** [comment]
@nuritgazit 
Should it stay or should it go?

**Comment by nuritgazit** [comment]
I think it should stay.
I honestly don't remember why we (I?) wanted to remove it.
It's not urgent, but we should have it back

**Comment by TheGrandVizier** [comment]
Back to dev for reinstatement of exit button.

**Comment by daonb** [comment]
WTF?

This is the first pull request we get from a complete outsider - @Scrump31.  We have a responsibility here and even if you can't remember why the button should go, you should trust the system - it's there for a reason.
If we are not sure it was a good idea, we should deploy and go back to the aquarium and see if people are missing the 'Exit Tree' button. If they do, open a new issue to recover the button.
