### ISSUE TITLE
Grey persons results for specific trees.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#145]
Some search results for specific treesa re displayed with a gray color.
http://prntscr.com/bpgmgn

If you enter the tree, the persons inside have their colors and information displayed correctly.
Something about this tree causes it to not be displayed correctly as results and subsequently, when added to a story.

Repro:
1. Search for tree number 3375

**Comment by daonb** [comment]
happens [here](http://dbs.bh.org.il/person?tree_number=7334) as well
