### ISSUE TITLE
User must scroll down in order to see and use all options of MJS bottom card.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#147]
The bottom row of cards in MJS, when interacted with, extend their drop-downs outside of the visible screen area.
The user must scroll down to remove these objects or assign them to some groups.
Unpleasant usability.

Reproduces:
1. Populate MJS with 4 rows of cards..
2. click the downward arrow on one of the cards on the bottom row.
Result:
You must scroll down to see all options.

**Comment by nuritgazit** [comment]
We decide to let this one go
