### ISSUE TITLE
Add luminaries from wikipedia

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-front#149]
An editor should be able to add a Wikipedia link thus creating a new luminary page.  The new page will be dynamically linked to the Wikipedia article so that whenever it changes so will our page. 

The new page will look just the current luminary page with the addition of a small note: "content by wikipedia" which will link to the article on Wikipedia.

**Comment by nuritgazit** [comment]
We need to close this issue and open a new one that refers to the larger definition of items from Wikipedia on our databases

**Comment by OriHoch** [comment]
@nuritgazit closed this issue to open a new one that refers to the larger definition of items from Wikipedia on our databases: #344
