### ISSUE TITLE
Trees modal appears again once search is complete.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#152]
The modal explaining person search reappears when the user completes a search.
It should only appear when the user arrives at the search page.

1. Arrive at search (modal appears)
2. Conduct a search
Result:
modal appears again with search results.

**Comment by TheGrandVizier** [comment]
This fix is not correct, @Inna-r 
Now the modal NEVER appears, even if the user doesn't click the "don't show this again".

I will clarify what needs to happen here:
1. First time user arrives at the person search, he gets the modal.
2. The user should get the modal every time he arrive at this search page, until he clicks "don't show this again".
3. HOWEVER, the user should **not** receive the modal if he is just using the search after arrving for the first time, even if he didn't opt-out.

**Comment by nuritgazit** [comment]
@TheGrandVizier, i just talked about it with @Inna-r, and she explained that after consulting with @daonb on how to do it, they decided to do it by the session.

This means that after the first time I close the modal I will not see it again as long as I'm in the same session. I know this wasn't the design, but I tend to agree this is less intrusive.

What do you think?

**Comment by TheGrandVizier** [comment]
Okey.
But does that mean that "Dont show again" is NOT per session?
If it is also per session, can we / should we get rid of it?

**Comment by nuritgazit** [comment]
Clicking on "Close" (or clicking outside the modal) = don't show again in this session.
Clicking on "Don't show again" = don't show again ever (unless cache is deleted)
