### ISSUE TITLE
Change our logo

### ISSUE THREAD

**Issue by Netush** [Beit-Hatfutsot/dbs-front#154]
Change the site logo (Hebrew & English) with the SVG logo 
(and update @nirgoldberg )

The new logo files you can find here:
https://www.dropbox.com/sh/8r5m3h10m0qoqxj/AAAMG7jVCEh-_VOhbDjl191-a?dl=0

Icon_Logo-BH-Eng.svg
Icon_Logo-BH-Heb.svg

**Comment by shivasheeshyadav** [comment]
@Netush @daonb I'll work on this.

**Comment by TheGrandVizier** [comment]
Is black and white on Edge / Explorer.
