### ISSUE TITLE
Quotation marks and possibly other characters are not displayed in persons (visible in results)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#163]
This is the URL of the example case:
http://dbs.bh.org.il/person/7577/I074

Here we can see how it looks in the tree and the tooltip:
http://prntscr.com/burq2b

In this image we can see how it looks on the result page:
http://prntscr.com/burqzi

**Comment by nuritgazit** [comment]
each browser is handling special characters differently. and we are not sure yet how to solve it. We want to try and wait for ClearMash and see if their encoding solutions solve this

**Comment by TheGrandVizier** [comment]
This has been fixed indirectly as a result of various changes that took place in the past.
