### ISSUE TITLE
Unable to close sharing URL box once open

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#164]
Once a user clicks on the sharing link button in "My story", the presented box containing the URL cannot be closed.
I think it should be closed if you click anywhere outside of it or on the button that shows it a second time.

**Comment by Inna-r** [comment]
The issue was solved by upgrading from ui-bootstrap 0.13.4. With the current ui-bootstrap version  the popover can be closed on outside click.
