### ISSUE TITLE
Google indexing (add site map)

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#17]

**Comment by nuritgazit** [comment]
@OriHoch I'm not sure it's actually needed, we are actually advertising the site using Google grants...?

**Comment by OriHoch** [comment]
it's very good for SEO to have a sitemap and send it to google

**Comment by daonb** [comment]
We need it as it helps users finds our content even if they're searching for a term we don't pay for.
IMO, this is a dbs-back issue.

**Comment by OriHoch** [comment]
done, 

sitemap is updated daily and available here - https://dbs.bh.org.il/sitemap/sitemap.xml

I also submitted it to google

you can see details and statistics from the last daily job that generated the sitemap here - https://api.dbs.bh.org.il/pipelines/
