### ISSUE TITLE
Change limit of items in MJS from 50 to 500 (for all Spotlights)

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#172]

**Comment by TheGrandVizier** [comment]
I need an admins credentials to test this.

**Comment by daonb** [comment]
There's no special interface for an editor... yet.
For now, being an editor just means that when someone asks for collection `paris` we'll collect the items under the `paris` branch your stories.

**Comment by TheGrandVizier** [comment]
yes but...

**Comment by nuritgazit** [comment]
@daonb I guess you will have to make @TheGrandVizier an editor :)

**Comment by TheGrandVizier** [comment]
No need. We already clarified this.
