### ISSUE TITLE
Enable Rich Social Sharing

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-front#182]
Sharing my story on facebook looks like this:

![selection_005](https://cloud.githubusercontent.com/assets/36852/17733305/a4057c82-647e-11e6-9720-cb839da3fb08.png)

In order to show the user's name and possibly one of the photos, we need to update the meta tags in the <head> with the relevant info. Once we have this on MJS and Items pages we will wire prerender.io to our nginx so social sites like facebook, twitter, outbrain, etc. will get a pre-rendered page.

**Comment by TheGrandVizier** [comment]
#165

**Comment by nuritgazit** [comment]
Change text to:

Title: [Name]'s Story
Text: Nurit's Jewish Story lives here. Find your photos, stories and more and learn how you are part of the story.

(current text): Nurit has collected photos, stories divided into the Mom's side, Dad's side, Bubu's side, Inspirational images branches.

**Comment by daonb** [comment]
@nuritgazit I need 4 pairs of title & description: English title & description when the user entered a name and another pair when there is no name and the same for Hebrew.

**Comment by nuritgazit** [comment]
**Case #1: User with name, English:**
Title: [Name]'s Story
Text: Nurit's Jewish Story lives here. Find your photos, family tree, stories and more and learn how you are part of the story.

**Case #2: User with name, Hebrew:**
כותרת: הסיפור של נורית
טקסט: הסיפור היהודי של נורית נמצא כאן. בואו לגלות את התמונות, עצי המשפחה וסיפורי הקהילה שלכם, ולהפוך להיות חלק מהסיפור.

**Case #3: User with no name, English:**
Title: This is My Jewish Story
Text: My Story lives here. Find your photos, family tree, stories and more and learn how you are part of the story.

**Case #4: User with no name, Hebrew:**
כותרת: הסיפור שלי
טקסט: הסיפור היהודי שלי נמצא כאן. בואו לגלות את התמונות, עצי המשפחה וסיפורי הקהילה שלכם, ולהפוך להיות חלק מהסיפור.
