### ISSUE TITLE
MJS should be HP for signed in users

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#184]

**Comment by daonb** [comment]
@nuritgazit just to clarify, signedin users have no way of accessing the wizard, right?

**Comment by nuritgazit** [comment]
They do - by clicking "Home"

**Comment by nuritgazit** [comment]
I'm sorry, but I regret this.
Please put back the old behaviour - HP should be the same for both logged in and logged out users.
Sorry, my bad, thank you.
