### ISSUE TITLE
Redesign Header

### ISSUE THREAD

**Issue by Inna-r** [Beit-Hatfutsot/dbs-front#185]

**Comment by daonb** [comment]
@Inna-r what's the status? can we close this?

**Comment by TheGrandVizier** [comment]
I cant test with no information.
What is this? what has been changed?
How should it look?
Reference to designs?
something? throw me a bone here.
"Redesign header" is not sufficient.

**Comment by Inna-r** [comment]
@TheGrandVizier 
1.display subheader on home page
2.in subheader separate dropdown tabs (recently viewed, search and upload) from regular ones
3. change main tab's name from ''my jewish story" - > "open databases"
