### ISSUE TITLE
[CZ] Kafka appears twice under luminaries

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#189]
In CZ Spotlight, Franz Kafka appears twice under the luminaries section.
It is probably added via two "admin" profiles.

**Comment by nuritgazit** [comment]
It was added to 2 of the Editor's account - Ushi's and Daniel's.
I deleted it from Daniel's

**Comment by TheGrandVizier** [comment]
Sorted and closed
