### ISSUE TITLE
CJH results are not visible outside of the museum.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#195]
Results from CJH are only visible through the museuems network.
Users from outside the museum will not see results from CJH.

This is problematic in many ways, mostly in terms of having two different experiences between museum and outside of it.

This brings forward another consideration. Perhaps it makes sense to show different things inside and outside, as it ties in to permissions / rights / museum - only stuff.

**Comment by nuritgazit** [comment]
@daonb Can you please update on the reasons for this (old dump, etc.)?

**Comment by nuritgazit** [comment]
@TheGrandVizier please move this issue to backend

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/dbs-back#32
