### ISSUE TITLE
Correct the "Add to my story" Button at Item Page (Hebrew & English)

### ISSUE THREAD

**Issue by Netush** [Beit-Hatfutsot/dbs-front#196]
There is no Hebrew version yet for this button and also The English version isn't fine 

![add-to-my-story](https://cloud.githubusercontent.com/assets/19781656/18437561/38eca244-7906-11e6-833b-6b157d385415.jpg)

The English version correction:
1 - The Plus icon and the V icon (at the toggle/Checked mode) should change (check the SVG link), and should be at the center of the white circle.
2 - The White circle should be little smaller (Check the image above). 
3 - Behavior change - The X mode is should be deleted (Currently when the button is toggled/Checcked and hover a large X appears at the white circle and clicking on which removes it from my story).
4 - Behavior change - a click on this button should open a choice to view item in my story and remove item at all clicks (also at the toggled/checked view - In my story). 

Link for SVG files: https://www.dropbox.com/sh/8r5m3h10m0qoqxj/AAAMG7jVCEh-_VOhbDjl191-a?dl=0

The SVG files you might need:
Icon_+
Icon_V
icon_Add to My Story-Eng
icon_Add to My Story-Eng-Hover
icon_Add to My Story-Heb
icon_Add to My Story-Heb-Hover
icon_In My Story-Eng
icon_In My Story-Eng-Hover
icon_In My Story-Heb
icon_In My Story-Heb-Hover

**Comment by Inna-r** [comment]
@Netush can you please add "Remove from my story" svgs (Eng, Heb)?

**Comment by Netush** [comment]
ok:
icon_Add to My Story-Remove-Eng
icon_Add to My Story-Remove-Heb
