### ISSUE TITLE
My email was cracked,how do I reset my password?

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-front#200]
There's no password, but let's not try and educate our users.

At the login popup add a short line at the bottom: "Your accounts were hacked? just click *here* to issue new credentials."

After clicking *here* the server will mark this user with a false `active`, add the role of `suspicious`  and show a message :  "Old credentials are now invalid."

**Comment by nuritgazit** [comment]
@TheGrandVizier @daonb @Netush 
i don't think we should trouble our users with terms such as "hacked and "credentials". 
We should go for the other option we talked in the morning, of having an expiry for the email link.
I say 30 minutes?

**Comment by TheGrandVizier** [comment]
Nurit, I feel 30 minutes is too little. I think 24 hours is more reasonable.

**Comment by nuritgazit** [comment]
Lets settle for 5 hours then?

**Comment by daonb** [comment]
:+1:

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/dbs-back#22
