### ISSUE TITLE
Nedd to be able to sort General Search results

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#213]
Currently, there is no way to sort General search results.
This makes it very hard to navigate through the results and find the right one.

The problem is, allowing sorting requires that all results be fetched at the same time, rather than delivering them in chunks. This requires an adaptation of how we fetch and deliver results.

This may also be helped by https://github.com/Beit-Hatfutsot/dbs-back/issues/24

**Comment by nuritgazit** [comment]
@Netush need design

**Comment by nuritgazit** [comment]
@TheGrandVizier to close?

**Comment by TheGrandVizier** [comment]
We gave up on this for now. Will resurrect if this becomes relevant in the future.
