### ISSUE TITLE
Include Family trees in general search results

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#214]
The general search should be... General, and include search results from family trees that are a good match.
This brings up questions of performance, as it basically doubles the amount of entries to search, or possibly even more than doubles.
I feel that consolidating these under general search with a result-filter tab of family trees is the way to go.

**Comment by nuritgazit** [comment]
@TheGrandVizier please move to backend

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/dbs-back#33
