### ISSUE TITLE
Internet Explorer Item page titles are not displayed correctly, exposed code visible.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#217]
Instead of all Item page titles, a user sees something along the lines of:
{{itemController.item_data.Header.En}} 

http://prntscr.com/ctbq3f

This happens for ALL items, regardless of type.
Additionally, the titles of the associated images are similarly compromised, as visible in the screenshot also.

**Comment by Inna-r** [comment]
@TheGrandVizier, what Internet Explorer version did you use?
