### ISSUE TITLE
Edit text on home page (Heb + Eng)

### ISSUE THREAD

**Issue by Inna-r** [Beit-Hatfutsot/dbs-front#225]
The En version:
"Welcome to My Jewish Story
THE OPEN DATABASES PROJECT
of The Museum of the Jewish People
Discover millions of pictures, family trees, music pieces, stories of communities and more"

**Comment by nuritgazit** [comment]
3 השורות הראשונות בסדר
את השורה האחרונה צריך לשנות ל:
גלו את הסיפור שלכם מתוך מליוני תמונות, עצי משפחה, קבצי מוזיקה, סיפורי קהילות ועוד

**Comment by nuritgazit** [comment]
3 השורות הראשונות בסדר
את השורה האחרונה צריך לשנות ל:
גלו את הסיפור שלכם מתוך מליוני תמונות, עצי משפחה, קבצי מוזיקה, סיפורי קהילות ועוד

**Comment by nuritgazit** [comment]
This is the location of Design with final text: 
Eng: https://projects.invisionapp.com/d/main#/console/904587/181123534/preview
Heb: https://projects.invisionapp.com/d/main#/console/904587/181283476/preview

We need to make sure that not only the text is fixed, but also the ways its displayed, breaks, etc.
