### ISSUE TITLE
"No results" error not displayed for consecutive family tree searches.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#227]
If a user searches for the same item that is not found more than once, only the first attempt produces an error notifying the user of a failed search.
Consecutive attempts will produce no response at all.

Reproduce:
1. Go to person search
2. Search for a tree number that does not exist (for example, 99999)
3. Search for the same tree again.

Result:
Only the first attempt produced an error notifying the user the search has failed.

**Comment by TheGrandVizier** [comment]
If I am to believe my console / network log, the second request is not even being sent if it is identical to the first.

**Comment by daonb** [comment]
IMO, the second request to search with exactly the same parameters should not search but rather produces a message: "Just searched that. Please review the results."
"בדיוק חיפשתי כאלו. אנא בדוק את התוצאות".
