### ISSUE TITLE
Example tree link in modal (hebrew) person search leads to a broken link.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#230]
The link to the example tree in the hebrew modal leads here:
http://dbs.bh.org.il/person/8888//I59594
Im not sure what the link SHOULD be, but i suspect it's this:
http://dbs.bh.org.il/person/8216/0/I52

This tree is not of great quality, so perhaps @nuritgazit would like to reconsider it's inclusion as an example.

**Comment by nuritgazit** [comment]
@Netush, do you happen to have the link to the original Hebrew tree?

**Comment by TheGrandVizier** [comment]
9798 is the new example tree fr hebrew, @Inna-r

**Comment by TheGrandVizier** [comment]
We have both overlooked an issue:
The link should lead to HEBREW interface of that tree.
So the correct link is:
http://dbs.bh.org.il/he/person/9798/I4321
and not
http://dbs.bh.org.il/person/9798/I4321
