### ISSUE TITLE
Add maps to places item page

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#234]

**Comment by Netush** [comment]
Sketch - Eng:
https://projects.invisionapp.com/d/main#/console/904587/206088744/preview
Heb:
https://projects.invisionapp.com/d/main#/console/904587/206112733/preview

**Comment by Netush** [comment]
![itempage-map](https://cloud.githubusercontent.com/assets/19781656/20702655/6496e820-b621-11e6-8d43-bc736bd6537e.jpg)

**Comment by nuritgazit** [comment]
@Inna-r please update status

**Comment by Inna-r** [comment]
@nuritgazit The map now displays current place item. We are working on updating all places items data with its coordinates to display markers on the map
