### ISSUE TITLE
Some persons display question mark icons isntead of birth / death dates even when they are available.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#239]
Some persons are displayed with question mark icons instead of birth and death years, even though this data exists and is displayed in the side bar.
Here is an example:
http://dbs.bh.org.il/he/person/9798/0/I4279
http://prntscr.com/dd7crb

**Comment by Inna-r** [comment]
@TheGrandVizier , i don't see any question mark icons in your example. Please retest

**Comment by TheGrandVizier** [comment]
Initially the dates will be correct but once you navigate to another person in the tree, the dates for that person will be black question marks, regardless of if the person has dates or does not.
