### ISSUE TITLE
Some thumbnails on result cards are not displayed (403)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#240]
Some thumbnails are not displayed on result card when using general search.
This is how it looks:
http://prntscr.com/ddjbo7

The missing images return a 403.
Reproduce:
1. Search for "The Rabbi of Bobowa"

**Comment by Inna-r** [comment]
I did a bit of research - the thumbnails exist, but not public.
@daonb how could we change this?

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/dbs-back#81
