### ISSUE TITLE
Clean all the search results when starting a new search

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-front#247]
Search for cohen, than type Reicher and press enter. just as press enter, you will see that our results are scraped and the europeana results appear at the top - " 2007 Results from Europeana".
These results should be removed at the same time we remove our own results.

**Comment by SanjayPatel16** [comment]
I would like to work on this issue. Can I please get some guidance?  I am new.

**Comment by Arvindkrishna1997** [comment]
can I work on the issue?;)
