### ISSUE TITLE
Bring back person data to person item card

### ISSUE THREAD

**Issue by Inna-r** [Beit-Hatfutsot/dbs-front#249]
After person data restructuring there are 4 missing data fields to restore and display on person card : 
- birth_date
- birth_place
- death_date
- death_place

**Comment by daonb** [comment]
Issue moved to [Beit-Hatfutsot/dbs-back #56](https://github.com/Beit-Hatfutsot/dbs-back/issues/56) via [**ZenHub**](https://www.zenhub.com/)
