### ISSUE TITLE
MJS issue with missing items.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#250]
An item that is missing from MJS is still counted towards the manually assigned Tab.
Here is an example:

http://prntscr.com/dm4z52

The missing item seems to be:
image_interior-of-the-syangogue-in-carpentras-france error_code: 404
I think this is a case where a header changed and the slug did not catch up.
I could not find an item with a matching header, but found a few that are suspiciously similar:
http://dbs.bh.org.il/search?q=carpentras&collection=images

Either way, the bug is not that it isn't found / displayed, the bug is that the tab's numeric indicator is not updated accordingly.

**Comment by Inna-r** [comment]
Issue moved to [Beit-Hatfutsot/dbs-back #59](https://github.com/Beit-Hatfutsot/dbs-back/issues/59) via [**ZenHub**](https://www.zenhub.com/)
