### ISSUE TITLE
Case where an item cannot be clicked via general

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#259]
When searched in the General Search, this item cannot be clicked.

Repro:

1. Search for Georgia in general search.
2. Click the search result for Georgia.
Result:
The result is not clickable.

**Comment by TheGrandVizier** [comment]
Another item that falls in this category is Biel.

**Comment by Inna-r** [comment]
@TheGrandVizier results for Georgia and Biel are actually clickable. Some other examples?

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/dbs-back#84
