### ISSUE TITLE
Print Mode to item page text and image

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#26]
Print image: https://projects.invisionapp.com/d/#/console/904587/148021530/preview 
Print item page: https://projects.invisionapp.com/d/#/console/904587/122529614/preview

**Comment by nuritgazit** [comment]
@Netush please check the links and also add the Ftree print mode link to design (and all other print mode types).

**Comment by TheGrandVizier** [comment]
Closing for duplicity
