### ISSUE TITLE
General Search Suggestions

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#279]
Suggestions from all DBs including Persons.

As the user is typing a search term, provide a list of suggestions that begin with what the user is typing.

Must suggest items of all types that are ours:

- Family names
- Places
- Luminaries
- Images
- Persons
- Compendium
- Stories
- Video
- Music

It should provide up to 5 suggestions as "Starts with".
If there is an exact match, suggest the exact match.

Future-proofing (bonus points): Add support for 5 items as "Sounds like".

**Comment by TheGrandVizier** [comment]
Invision link

https://projects.invisionapp.com/d/main#/console/904587/206067616/preview

**Comment by TheGrandVizier** [comment]
backend https://github.com/Beit-Hatfutsot/dbs-back/issues/118

**Comment by OriHoch** [comment]
this issue will deal with showing whatever the backend returns

from the frontend side - all this issue cares about is sending a (partial) search term and getting back a list of suggestions, c'est tout

this means that frontend can start development without waiting for backend - the interface itself is very simple, so will be easy to change the specifics of it later

**Comment by TheGrandVizier** [comment]
This is the correct invision link

**Comment by OriHoch** [comment]
###### comment from @Netush (moved from PR #358)
The Search Suggestion Should look like this:
English:
https://projects.invisionapp.com/d/main#/console/904587/206067616/preview
Hebrew:
https://projects.invisionapp.com/d/main#/console/904587/206067617/preview

Articles include Places, Family Names & Compendium Databases
People include Family Trees, Luminaries & Stories Databases
Media include Images, Videos & Music Databases

**Comment by OriHoch** [comment]
thanks @Netush 

some things are not clear to me (possibly to be answered by @Inna-r / @TheGrandVizier) - 
* currently the backend returns 5 results for each collection, out of the following collections: personalities, places, persons, movies, photoUnits, familyNames
* in the mapping of types to collection in @Netush comment above, I didn't see a reference to all the above collections (at least not by the names I am familiar with)
* also, I see some mapping to collections which we don't have yet
* what's the logic of combining the results? for example, say we have results that return 5 places, 5 family names and 5 compendiums - all these collections should be displayed under articles - how will they be merged? also, I guess it won't look good to show 15 items, so the list will need to be truncated - how?
* there could still be a scenario where results from different collections will have the same title under the same type (e.g. under Articles - have a place called Paris and a compendium article called Paris) - are we 100% sure there aren't and won't be situations like this? or we don't care?

this is just some thoughts not clear to me, if it's clear to you (e.g. to @Inna-r , @TheGrandVizier  and @Netush) - that's fine with me.. you don't need to clarify it

**Comment by Netush** [comment]
Some clarification:
Articles include Places & Family Names Databases (in the future also Compendium)
People include Family Trees & Luminaries Databases (in the future also Stories)
Media include Images & Videos Databases (in the future also Music)

The maximum suggestion for each categories (Articles, People & Media) should be six ,the return suggest for each sub-Category should be equal, the sorting should be by relevancy.

**Comment by Netush** [comment]
About the scenario that it can be suggestion with the same title
Same title under different categories is fine but under one category no - there shouldn't be the same title

![hp1a](https://cloud.githubusercontent.com/assets/19781656/25845768/cd3886c6-34b7-11e7-9839-32a68e61eff5.jpg)

**Comment by OriHoch** [comment]
thanks @Netush - in case there are 2 titles under same category - how do we decide which one to show?

**Comment by Netush** [comment]
It doesn't really matter - because after the user choose a suggestion it goes to general search results and there will be all results

**Comment by Inna-r** [comment]
@TheGrandVizier  wizard search and general search share the same service that brings suggestions. check both search boxes please
