### ISSUE TITLE
general search should include results from family trees (Move Family Tree tab from main toolbar to results tabs)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#280]
Add filters for:

- First name 
- Last name (Exact, Starts with, Sounds like)
- Sex (Male, Female, Nevermind)
- Place of birth (Exact, Starts with, Sounds like)
- Place of marriage (Exact, Starts with, Sounds like)
- Place of death (Exact, Starts with, Sounds like)
- Year of birth (Exact, +/-1 year, +/-2 years, +/-3 years)
- Year of marriage (Exact, +/-1 year, +/-2 years, +/-3 years)
- Year of death (Exact, +/-1 year, +/-2 years, +/-3 years)
- Tree number

Invision link:
https://projects.invisionapp.com/d/main#/console/904587/214538825/preview

**Comment by TheGrandVizier** [comment]
awaits backend

**Comment by OriHoch** [comment]
backend issue - Beit-Hatfutsot/dbs-back#33 - will add support for using the general search API to get results from family trees as well. On frontend it should simplify things as you will need to contact a single general search API for all search needs both general and family trees

**Comment by OriHoch** [comment]
following this logic of same search API used for family trees as well - frontend can start development
you can assume the search API will work the same way it does today just adding details about people (family trees)

**Comment by TheGrandVizier** [comment]
Another backend issue for this related:
https://github.com/Beit-Hatfutsot/dbs-back/issues/119

**Comment by OriHoch** [comment]
backend issue is done and deployed to test environment
API documentation is available here: http://devapi.dbs.bh.org.il/v1/docs#database-search-persons-advanced-search

**Comment by TheGrandVizier** [comment]
This is done, but resulted in this:
https://github.com/Beit-Hatfutsot/dbs-front/issues/348
