### ISSUE TITLE
Change item type indicator from animated strip to red icon in front of header

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#285]
The same icons that are used right now in the category strips per item type is to be used, only in red and placed before the title of the item card instead of on strip dedicated to it.

https://projects.invisionapp.com/d/main#/console/904587/214538829/preview

**Comment by Netush** [comment]
![card-change1](https://cloud.githubusercontent.com/assets/19781656/23204518/93e07b3a-f8ef-11e6-851b-60b9417c04ce.jpg)

SVG Files you can find here:
https://www.dropbox.com/sh/8r5m3h10m0qoqxj/AAAMG7jVCEh-_VOhbDjl191-a?dl=0

Here is the files you need:
Family Name.svg
Family Tree.svg
Place.svg
Luminary.svg
