### ISSUE TITLE
Selected Item indicator on header should have triangular bottom

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#288]
#### reproduction steps
* open dbs.bh.org.il
* click on search in header menu (home / my story / family trees / search / recently viewed)

##### expected
* selected item should be selected with red background
* selected item should have an triangular bottom as specified in the design - 
![image](https://cloud.githubusercontent.com/assets/1198854/23203436/2a87587e-f8eb-11e6-932d-7dda7e889179.png)

##### actual
* selected item have a red background but no triangular bottom

**Comment by OriHoch** [comment]
tested on production, looks good
