### ISSUE TITLE
Add font resize option to item page

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#292]
as per design, there should be a font resize option with 3 sizes available.
@Netush can you provide the actual font sizes for each option please?

**Comment by Netush** [comment]
Small size (default) - 18 PX
Medium size - 22 PX
Large size - 26 PX

Font sizes are clickable:
https://projects.invisionapp.com/d/main#/console/904587/206092962/preview

**Comment by TheGrandVizier** [comment]
Does not work, please address @Inna-r

**Comment by OriHoch** [comment]
@Inna-r please handle at top priority because we already deployed a version (0.11.4) where it should have worked, and where the relevant code was already deployed
