### ISSUE TITLE
"Expand Image" button on item page

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#293]
Under the image, we would like to have a button that expands it and shows more of the image.
As per invision mockup.

**Comment by Netush** [comment]
https://projects.invisionapp.com/d/main#/console/904587/206088744/preview

SVG Files you can find here:
https://www.dropbox.com/sh/8r5m3h10m0qoqxj/AAAMG7jVCEh-_VOhbDjl191-a?dl=0

Files:
Triangle.svg
Choopchick.svg
