### ISSUE TITLE
Item page sharing tools

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#294]
Implement Twitter, Facebook and Email buttons and relevant sharing to item page.

**Comment by Netush** [comment]
https://projects.invisionapp.com/d/main#/console/904587/206092962/preview

SVG Files you can find here:
https://www.dropbox.com/sh/8r5m3h10m0qoqxj/AAAMG7jVCEh-_VOhbDjl191-a?dl=0

Files:
Facebook.svg
Twitter.svg
Email.svg
