### ISSUE TITLE
Printable version / Print button

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#296]
The print button should take the user to a printable version of the page and give him an option to print it.

**Comment by Netush** [comment]
https://projects.invisionapp.com/d/main#/console/904587/206092962/preview

**Comment by nuritgazit** [comment]
@TheGrandVizier 
Duplication with" Print Mode - For item page & Family tree #175".
Need to decide which of them is more up to date, and close the second one.

**Comment by TheGrandVizier** [comment]
https://github.com/Beit-Hatfutsot/dbs-front/issues/175
