### ISSUE TITLE
should have a high quality image / sprite for selected item in header

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#309]
according to design, selected item in header should have a rectangular bottom like this:
![image](https://cloud.githubusercontent.com/assets/1198854/23203436/2a87587e-f8eb-11e6-932d-7dda7e889179.png)

current implementation (#308) uses the following background image to do that:
![image](https://raw.githubusercontent.com/Beit-Hatfutsot/dbs-front/02134872478fd0b89ffc8bf3a08bb2705968e85e/images/header-item-bg.png)

need to have a better quality version of this background image

guidelines for this image:
* image is stretched / sized-down to the menu item size, this is done in the browser so need to provide a background image close to the actual size as possible
* need to have a transparent bottom, can use a png with alpha transparency layer to support differently colored backgrounds

**Comment by Netush** [comment]
Files you can find here:
https://www.dropbox.com/sh/8r5m3h10m0qoqxj/AAAMG7jVCEh-_VOhbDjl191-a?dl=0

Files:
Triangle Buttom.svg
Triangle Buttom.png

**Comment by OriHoch** [comment]
thanks
