### ISSUE TITLE
(SEO) Create a 301 redirect

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#311]
SEO requests that we create a 301 redirect from dbs.bh.org.il to www.dbs.bh.org.il

**Comment by TheGrandVizier** [comment]
@OriHoch @daonb  Is there any reason not to do this?
Speak now or for ever hold your piece.
This was requested by the SEO company.

**Comment by Libisch** [comment]
@TheGrandVizier SEO request was cancelled, right?

**Comment by TheGrandVizier** [comment]
Correcto.
