### ISSUE TITLE
Wrong image title on home page.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#322]
On the homepage, we display a background image. That image has a titled link leading to it's item page.
The link reads: Girls soldiers standing on a truck.
It should be changed to "Female soldiers standing on a truck".

`<a ui-sref="item-view ({collection: 'image', local_slug: 'girls-soldiers-standing-on-a-truck-israel-1950s'})" class="ng-scope" href="/image/girls-soldiers-standing-on-a-truck-israel-1950s">Girls soldiers standing on a truck, Israel 1950s.</a>`

Should be 
`<a ui-sref="item-view ({collection: 'image', local_slug: 'girls-soldiers-standing-on-a-truck-israel-1950s'})" class="ng-scope" href="/image/girls-soldiers-standing-on-a-truck-israel-1950s">Female soldiers standing on a truck, Israel 1950s.</a>`

The title of the image has changed but the slug remains. However, the visible title on the homepage must be changed.

**Comment by OriHoch** [comment]
@TheGrandVizier I see that the related pull request is closed, what's the status of this issue?

**Comment by TheGrandVizier** [comment]
Sorry, forgot to move to WIP. All sorted now. Ready for prod.
