### ISSUE TITLE
Update text in About Family Names page

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#324]
This page: 
[Hebrew](http://dbs.bh.org.il/he/%D7%90%D7%95%D7%93%D7%95%D7%AA/familyNames)
[English](http://dbs.bh.org.il/about/familyNames)

Should have the same text as this page:
[Hebrew](http://www.bh.org.il/he/%D7%9E%D7%90%D7%92%D7%A8%D7%99%D7%9D-%D7%95%D7%90%D7%95%D7%A1%D7%A4%D7%99%D7%9D/%D7%A9%D7%9E%D7%95%D7%AA-%D7%9E%D7%A9%D7%A4%D7%97%D7%94/%D7%9E%D7%90%D7%92%D7%A8-%D7%A9%D7%9E%D7%95%D7%AA-%D7%94%D7%9E%D7%A9%D7%A4%D7%97%D7%94-%D7%9E%D7%91%D7%95%D7%90/)
[English](http://www.bh.org.il/databases/family-names/jewish-family-names-introduction/ )

**Comment by OriHoch** [comment]
#### reproduction steps
* open [about family names hebrew](http://dbs.bh.org.il/he/%D7%90%D7%95%D7%93%D7%95%D7%AA/familyNames) or [about family names english](http://dbs.bh.org.il/about/familyNames)

##### expected
* the main page text (not including side-bar / header / footer) should show the text from the www.bh.org.il site:
  * [Hebrew](http://www.bh.org.il/he/%D7%9E%D7%90%D7%92%D7%A8%D7%99%D7%9D-%D7%95%D7%90%D7%95%D7%A1%D7%A4%D7%99%D7%9D/%D7%A9%D7%9E%D7%95%D7%AA-%D7%9E%D7%A9%D7%A4%D7%97%D7%94/%D7%9E%D7%90%D7%92%D7%A8-%D7%A9%D7%9E%D7%95%D7%AA-%D7%94%D7%9E%D7%A9%D7%A4%D7%97%D7%94-%D7%9E%D7%91%D7%95%D7%90/)
  * [English](http://www.bh.org.il/databases/family-names/jewish-family-names-introduction/ )
* only the main page text is needed, format and design are not important, just copy the text and headings

##### actual
* only a single paragraph is displayed

**Comment by OriHoch** [comment]
@nuritgazit - please approve my previous comment to ensure I understood correctly what's needed..

**Comment by nuritgazit** [comment]
@OriHoch approved, but I think @Libisch is on it? we talked about it briefly yesterday, but maybe you are too quick for her

**Comment by OriHoch** [comment]
I'm not saying I will do it, I'm just making sure we have backlog of issues ready for work
@Libisch - please assign yourself to an issue if you are working on it

**Comment by Libisch** [comment]
@OriHoch @nuritgazit @TheGrandVizier 
Text was added but we must not redirect until SEO is applied to these pages. The SEO guys are working on it.

**Comment by OriHoch** [comment]
@Libisch 
I don't see any reason not to move forward with this issue - it is not dependent on the SEO issue 

(moving forward = merging the fix / testing / deploying )
