### ISSUE TITLE
Family Name search box at Family Trees Hebrew page should show Einstein (instead of Kafka)

### ISSUE THREAD

**Issue by Netush** [Beit-Hatfutsot/dbs-front#325]
* [family trees hebrew page](http://dbs.bh.org.il/he/person)
* look at the family name text box (שם משפחה)

##### expected
* כהן, אינשטיין...

##### actual
* ![image](https://cloud.githubusercontent.com/assets/1198854/24137911/99212fba-0e1e-11e7-86f8-0570e7d86e0d.png)

**Comment by OriHoch** [comment]
@Netush - you can test on test
and on production after the deployment today

**Comment by OriHoch** [comment]
tested on produciton, looks good
