### ISSUE TITLE
item page after using the wizard should be displayed correctly

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#326]
### reproduction steps
* open the dbs homepage
* use the wizard (fill-in last name / place)
* search
* now, go back to homepage and use the "general search"
* go to a place item page

#### expected
* displayed normally

#### actual
* page is broken
![image](https://cloud.githubusercontent.com/assets/1198854/23955149/c9f129f0-09a1-11e7-80a9-4820831b6046.png)

**Comment by OriHoch** [comment]
fixed @ 0.11.2

@TheGrandVizier  - It's a quick and dirty css fix.. haven't tested fully myself, please test well

(deploying to stage as I'm writing this comment)

**Comment by OriHoch** [comment]
fixed broken layout when showing in hebrew (@ 0.11.3)

**Comment by TheGrandVizier** [comment]
The english was fixed, but the hebrew was not.
In hebrew, icons overlap text in the boxes:
http://prntscr.com/em8jqm

**Comment by OriHoch** [comment]
fixed just before you sent the comment :+1:

**Comment by TheGrandVizier** [comment]
Yes, confirmed, fixed.

**Comment by OriHoch** [comment]
tested on production, looks good

**Comment by TheGrandVizier** [comment]
Verified on prod
