### ISSUE TITLE
Optimize Facebook sharing

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#328]
Currently the facebook sharing of an item page shares an undesigned and unoptimized post which does not show anything or indicate anything about it's content using preview.

- Add preview image
- Add preview text / description

**Comment by nuritgazit** [comment]
@daonb aren't we paying for a service in order to avoid just what @TheGrandVizier is describing?

**Comment by OriHoch** [comment]
@TheGrandVizier - please add some details:
* be more specific what is wrong with current content
* is it the same problem on all pages? only on specific pages?
* what is the expected image/title/description for each page? (could be the same for all pages if you want, but need to define it)

**Comment by nuritgazit** [comment]
@daonb ?

**Comment by daonb** [comment]
We are paying for prerender.io to do it. It seems to be working for me: In facebook I pasted the address of our paris page and that's what I got:
![sharing_paris](https://cloud.githubusercontent.com/assets/36852/24191276/008934b0-0ef4-11e7-8900-2308d473f932.png)

**Comment by TheGrandVizier** [comment]
The problem exists only on test apparently.
On prod, the sharing trools work correctly.
On test, this is what happens:
http://prntscr.com/en0jcq
Top is test, bottom is prod.

**Comment by daonb** [comment]
That's because wqe don't pay prerender to prepare the pages on the test server.

**Comment by TheGrandVizier** [comment]
Ok. Considering fixed.
