### ISSUE TITLE
Last names in trees are only displayed for the first person to be viewed

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#329]
Trees currently only display last names for the first person to be viewed in a tree, with some exceptions.

Reproduce:
1. Search for Naftali Bennett in tree 12295 (http://test.dbs.bh.org.il/person/12295/0/I8)
2. Navigate to his grandfather, Samuel. Note there is no last name.
3. Refresh the page while focused on Samuel.

Result:
Last name for Samuel displayed as Bennett.

Expected result:
Last name displayed for all persons when entering a tree.

Also, an error appears in the log:
http://prntscr.com/ema5fy

Note: Persons directly above those in focus retain their last name.

**Comment by OriHoch** [comment]
fixed in dbs-front release 0.12.0 (deployed to test)

please see if this fixes it / if you can find more scenarios..

**Comment by OriHoch** [comment]
tested on production (http://dbs.bh.org.il/person/12295/0/I8), looks good

**Comment by TheGrandVizier** [comment]
Verified on prod
