### ISSUE TITLE
Family tree display optimization for longer names.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#330]
The trees currently do not display long names or multiple names too well.

http://prntscr.com/emkhmv

Reproduce:
1. Go to Naftali's tree:  http://test.dbs.bh.org.il/person/12295/0/I6
2. Look at Naftali's children.

Expected result:
All names visible for every person.

Actual result:
One out of three names displayed for children, the rest do not fit in the display.

This may require a slight redesign or at least designs input, @Netush  @nuritgazit 
This is a result of adding all names to be displayed. Now we realize there was a reason we did not display all.

**Comment by OriHoch** [comment]
@TheGrandVizier - I think it can be solved easily by reducing line height (minimizing spaces between lines) and reducing font-size, I'll try and will see how it looks

**Comment by Netush** [comment]
the text size should not be reduce - but only the first name should appear at that capsule size  (full name appear when hover)

**Comment by OriHoch** [comment]
gotcha, I'll see what I can do

**Comment by OriHoch** [comment]
fixed and deployed to production
http://dbs.bh.org.il/person/12295/0/I6
