### ISSUE TITLE
General search displays results we are not allowed to display. Items produce 403.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#332]
There are some items in BHP we are not supposed to show because the museum does not own rights for it.
In theory, these items should never even be migrated to to start with.
Attempting to display the item page fails with 403.

Reproduce:
1. Search for Cohen: http://test.dbs.bh.org.il/search?q=cohen
2. Find the result labeled "Mr Cohen, Mrs Cohen": http://prntscr.com/emmu9g
3. Click the result

Expected result:
Taken to item page

Actual result:
Page fails to load, notified of 403 (forbidden):
http://prntscr.com/emmup9

**Comment by OriHoch** [comment]
Issue moved to [Beit-Hatfutsot/dbs-back #129](https://github.com/Beit-Hatfutsot/dbs-back/issues/129) via [**ZenHub**](https://www.zenhub.com/)
