### ISSUE TITLE
Family trees- Hebrew cards of female change text

### ISSUE THREAD

**Issue by Netush** [Beit-Hatfutsot/dbs-front#335]
At the family trees cards when a female have the date or place of birth or death 
Need to change the text: "נולד" to "נולדה" and "נפטר" to "נפטרה"
![ftree-24](https://cloud.githubusercontent.com/assets/19781656/24195216/8a814934-0f01-11e7-9274-42d2394162ec.jpg)
![ftree-25](https://cloud.githubusercontent.com/assets/19781656/24195217/8b9ce80a-0f01-11e7-8e08-25129d465ae8.jpg)

**Comment by OriHoch** [comment]
fixed, deployed to test:
http://test.dbs.bh.org.il/he/person?first_name=%D7%91%D7%9C%D7%94&last_name=%D7%9C%D7%96%D7%A8%D7%95%D7%91
