### ISSUE TITLE
Duplicated item in Related 

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#336]
This is how it happened to me:
1. Searched for צ'רני
2. Entered the Luminary item in English Leon [http://dbs.bh.org.il/luminary/charney-leon-harris](url)  
3. The item New York appears twice under Related

![image](https://cloud.githubusercontent.com/assets/19633598/24198942/91c912da-0f10-11e7-9a06-c10761ba6f60.png)

**Comment by TheGrandVizier** [comment]
Known, already exists here:
