### ISSUE TITLE
hebrew text at bottom of item page regarding data source should not be reversed

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#337]
* open http://dbs.bh.org.il/he/%D7%A6%D7%A8%D7%A0%D7%99-%D7%9C%D7%90%D7%95%D7%9F-%D7%94%D7%90%D7%A8%D7%99%D7%A1/%D7%90%D7%99%D7%A9%D7%99%D7%95%D7%AA
* look at the hebrew text just below add to my story / continue reading

#### expected
* טקסט רשמי שנכתב ע“י חוקרים שלנו - מוזיאון העם היהודי בבית התפוצות

#### actual
* תוצופתה תיבב ידוהיה םעה ןואיזומ - ונלש םירקוח י“ע בתכנש ימשר טסקט
![image](https://cloud.githubusercontent.com/assets/1198854/24353561/caaadf40-12f6-11e7-8111-9c4f8d1deb89.png)

**Comment by Libisch** [comment]
Fixed, sent pull request.
