### ISSUE TITLE
Item display filtering

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#343]
Following a problem with Ftrees that weren't supposed to be displayed, we need to go over the list of filtering rules and make sure all is done properly.
Haim has updated the list and its save [here](https://drive.google.com/open?id=0B6aHDT7jKnxkby1feDFCYVJjSHM)

**Comment by OriHoch** [comment]
Issue moved to [Beit-Hatfutsot/dbs-back #155](https://github.com/Beit-Hatfutsot/dbs-back/issues/155) via [**ZenHub**](https://www.zenhub.com/)
