### ISSUE TITLE
Wikipedia Integration

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#344]
High level design is [here](https://docs.google.com/document/d/11-6WMgyMp7WJ-ZvRniqIwsQpQaDWXxRSjXst541k0ME)
Design is [here](https://projects.invisionapp.com/d/main#/console/904587/227710266/preview)
Definition is [here](https://drive.google.com/open?id=1IElqRjjbduOE0p7kcKKlWCAjGikVFvEkmwUvl1dHHpU)

**Comment by nuritgazit** [comment]
@daonb please add a link to the document you created

**Comment by daonb** [comment]
Added it at the top of the description

**Comment by OriHoch** [comment]
needs tech design - ~2-3 points

**Comment by OriHoch** [comment]
Issue moved to [Beit-Hatfutsot/beit-hatfutsot-devops #19](https://github.com/Beit-Hatfutsot/beit-hatfutsot-devops/issues/19) via [**ZenHub**](https://www.zenhub.com/)
