### ISSUE TITLE
Add Terms of Use

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#345]
We need to add the Hebrew and English Terms of Use to the DBs site.
The TOU should appear in a page of their own, each for each language.
The link to the page would appear in the footer, to the left of "Help us enrich" (English) and to the right of "עזרו לנו".
The text are [here](https://drive.google.com/open?id=0B6aHDT7jKnxkQWVNT25MTW8xTlU)

**Comment by OriHoch** [comment]
same design as about / generic pages like http://dbs.bh.org.il/about/familyTree

**Comment by Libisch** [comment]
@OriHoch Done, Please review.

**Comment by TheGrandVizier** [comment]
I.... Don't see it.
@Libisch

**Comment by TheGrandVizier** [comment]
Does this not work, or is is it just not deployed? @Libisch

**Comment by Libisch** [comment]
Merged. Following @TheGrandVizier review, reopening issue to fix minor text Issue #361
