### ISSUE TITLE
Disable Europeana Search Results

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-front#346]
When [searching for Przemysl](http://test.dbs.bh.org.il/search?q=Przemysl) we get results from europeana results that clicking them leads content that does not exist.

**Comment by nuritgazit** [comment]
Looks like a bug on their side, but I'll leave it to @TheGrandVizier to decide

**Comment by OriHoch** [comment]
I don't see any problem with Europeana
@daonb - please be more specific about the problem you see

**Comment by nuritgazit** [comment]
@TheGrandVizier it looks like the links to europeana results lead to actual pages, but all of them are empty.

**Comment by nuritgazit** [comment]
The pages on Europeana side are ok, only look bad. I'm closing this bug
