### ISSUE TITLE
The main general search query field does't work well with persons filters fields

### ISSUE THREAD

**Issue by Inna-r** [Beit-Hatfutsot/dbs-front#348]
General 'Persons search' considers main query as last or first name ("Paris" also will be searched in person's name), so if one of these fields is filled inside filters form we got no results.
Reproduce:
- search for Cohen
- put some other family or first name in filters fields.

**Comment by OriHoch** [comment]
I think it's a design issue @Netush @TheGrandVizier

**Comment by TheGrandVizier** [comment]
What needs to happen here is the following:
Each new **General** search searches everything, **all DBs**, as it's name indicates.

**Filtering** the search results **does not** need to repeat a general search in all DBs, but just the relevant ones fTrees? Persons?).

I am starting to think that under the hood, for you, filtering and searching is the same thing and it's just about where the search takes place?

@OriHoch can you confirm, deny, or otherwise comment?

**Comment by OriHoch** [comment]
I don't understand, please write at least 1 example with clear reproduction steps, expected behavior and actual behavior

**Comment by TheGrandVizier** [comment]
The filters should ignore the original search and only be applied on the results of that search.

Scenario 1:
1. Search for Cohen in general search, get results.
2. Go to "Person" tab. Filters now visible.
3. Apply a filter. Name: Levi.
4. Click "Filter".

Result:
Results displayed are narrowed down from previous batch (Cohen-containing trees) to only people with Levi in their name in moscow.

**Comment by TheGrandVizier** [comment]
@Inna-r  updated issue

**Comment by TheGrandVizier** [comment]
@OriHoch Inna says this is a backend bug.
Can we please get some clarity on this issue?

**Comment by OriHoch** [comment]
@Inna-r please open a corresponding backend bug

**Comment by OriHoch** [comment]
@Inna-r @TheGrandVizier I suggest to open new issue for every bug, it's very hard to track the problem..

@TheGrandVizier - regarding your reproduction steps - I don't see a problem there
when you do a general search query for "Moscow", none of the results have a person named "Levi" -  hence no results - this is valid


@Inna-r - regarding your description, I didn't fully understand what is you expected results

in any case, I opened a dbs-back issue with a possible problem:

Beit-Hatfutsot/dbs-back#181

feel free to close this issue if the backend issue covers all your problems..

**Comment by TheGrandVizier** [comment]
Thanks, indeed it does. Closing this.
