### ISSUE TITLE
Update scan of an item 

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#350]
@OriHoch Haim is asking to display a new scan they added to for item ID 160561.
He also claims the current scan is flawed, you get a 403 error when trying to access it: 
http://dbs.bh.org.il/image/dora-and-leo-hamerman-new-jersey-usa-1987

This is for the donor of the image, so they are waiting for our update.

**Comment by nuritgazit** [comment]
@OriHoch this is kind of urgent, would you be able to fix it soon?

**Comment by TheGrandVizier** [comment]
While we are at it, lets also migrate Warsaw.

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/dbs-back#159
