### ISSUE TITLE
Technical document for collaborations

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#357]
We need a technical document that describes the 2 ways we can collaborate with different institutions in the DBs - rest API / Data Dump.
Using this document, Ronen's team can approach potential collaborators and instruct them on what to do so that we can integrate their content on our search.
@daonb, I think you are the natural candidate for that...?

**Comment by OriHoch** [comment]
Issue moved to [Beit-Hatfutsot/beit-hatfutsot-devops #18](https://github.com/Beit-Hatfutsot/beit-hatfutsot-devops/issues/18) via [**ZenHub**](https://www.zenhub.com/)
