### ISSUE TITLE
Merge Video and Images "About" page and it's links

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#371]
Reproduce
1. Scroll down to the footer of page on dbs.bh.org.il

Actual result:
1. Image archive has a link to it's "about" page.
2. Video archive has a link to it's "about" page.

Desired result:
1. One link for both, named "Visual Documentation" / תיעוד חזותי
2. The text on both about pages is already the same.

**Comment by Libisch** [comment]
<img width="461" alt="screen shot 2017-05-14 at 12 58 20" src="https://cloud.githubusercontent.com/assets/20017334/26032814/1aff36a2-38a5-11e7-8464-d9a877347c37.png">

**Comment by Libisch** [comment]
#373 Merged.
