### ISSUE TITLE
people search should filter according to first name exacts or begins with

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#375]
### reproduction steps
* goto general search: http://test.dbs.bh.org.il/search
* type `hoch` into general search box, click the search icon
* get back some results for "Hoch"
* click on People (Family trees) tab
* see that one of the results is for "Lea Hoch"
* enter "Lea" into the First Name filter
* choose "exact" or "begins with" in the first name search type
* filter

#### Expected
* "Lea Hoch" should appear in results

#### Actual
* No results

### notes
* it works when you chose search type of `Sounds Like`

**Comment by Inna-r** [comment]
@OriHoch 'people search' takes 'exact' for non-numeric fileds by default.
Apparently it's case sensitive - it works well for 'lea' and doesn't work for 'Lea'.

**Comment by OriHoch** [comment]
if this is a backend issue, please open an issue for backend and try to describe there specifically which backend API url is being accessed and what's the expected / actual outcome

**Comment by Inna-r** [comment]
@TheGrandVizier fixed in  [#174](https://github.com/Beit-Hatfutsot/dbs-back/issues/174)
