### ISSUE TITLE
print page should not show buttons / links - only the text

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#380]
### reproduction steps
* go to an item e.g. http://test.dbs.bh.org.il/familyname/berlin
* click the little arrow below the main image
* click the print button

#### expected
* 
![image](https://cloud.githubusercontent.com/assets/1198854/26094230/c7d9e962-3a21-11e7-8223-9a31918ab990.png)

#### actual
* buttons / links appear
* partial text is shown with continue reading link (try clicking that on paper!)

**Comment by TheGrandVizier** [comment]
Duplicate

https://github.com/Beit-Hatfutsot/dbs-front/issues/175
