### ISSUE TITLE
API should only allow access to items with full internet rights

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#381]
the item 26559 from BHP, that has no internet rights, and does not appear on the DBs site (which is good), does appear in search results on CJH (which is not good)

**Comment by OriHoch** [comment]
Issue moved to [Beit-Hatfutsot/beit-hatfutsot-devops #22](https://github.com/Beit-Hatfutsot/beit-hatfutsot-devops/issues/22) via [**ZenHub**](https://www.zenhub.com/)
