### ISSUE TITLE
family trees search: viewing person in tree from search results should work

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#382]
### reproduction
* general search for "בלה כהן"
* click on People tab
* in the results - click on "בלה כהן"
* 
![image](https://cloud.githubusercontent.com/assets/1198854/26095154/4fa0e9b0-3a25-11e7-9b7c-d01893903daf.png)

#### expected
* see "בלה כהן" in family tree

#### actrual
* nothing is shown
* network tab shows 404 error from API
* 
![image](https://cloud.githubusercontent.com/assets/1198854/26095175/6937fd6e-3a25-11e7-913c-cb42fd62550c.png)

**Comment by OriHoch** [comment]
opening the same person from the "old" family trees tab works - 
http://test.dbs.bh.org.il/person/10822/0/I104

**Comment by TheGrandVizier** [comment]
This was a duplicate:
https://github.com/Beit-Hatfutsot/dbs-front/issues/398
