### ISSUE TITLE
hebrew only: general search suggestions section titles should show translation of english section titles

### ISSUE THREAD

**Issue by Libisch** [Beit-Hatfutsot/dbs-front#384]
- English divides results by collections, but doesn't indicate "Starts with"
- Hebrew results are divided but without indication
- The dividing text is `מתחיל מ` - should be `מתחיל ב`.
<img width="207" alt="screen shot 2017-05-16 at 17 27 37" src="https://cloud.githubusercontent.com/assets/20017334/26111200/2dc4a916-3a5d-11e7-8f7d-bd860745d8e9.png"><img width="207" alt="screen shot 2017-05-16 at 17 28 03" src="https://cloud.githubusercontent.com/assets/20017334/26111228/3f71c3e2-3a5d-11e7-8d88-0f2404d3baa6.png">

@TheGrandVizier I guess expected result should be decided upon ("Starts with in places:" or only "Places" with one "Starts with" located on top?), followed by new updated issues.

**Comment by OriHoch** [comment]
### reproduction steps
* go to hebrew site
* start typing in search box
* look at suggestion sections

#### expected
* section names should be in hebrew: מקומות / כתבות ...

#### actual
* all sections show מתחיל מ:
