### ISSUE TITLE
Investigate CJH Rights and Usage

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#392]
CJH somehow have exposed items they (and us) have no rights to.

- [ ] Investigate how this happened
- [ ] Prevent this from happening again

@nuritgazit can you provide the original example of this not working right?

**Comment by nuritgazit** [comment]
yes, @TheGrandVizier - it is here: https://github.com/Beit-Hatfutsot/beit-hatfutsot-devops/issues/22#issuecomment-301707261
