### ISSUE TITLE
The "No Results" report should include Person / tree filters

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#394]
Reproduce:
1. Search for "Nikolai" in general search
2. Go People tab
3. Add filter: Place: Jaffa
4. Click "Filter"

Expected result:
Receive message that says there is no results for Nikolai that was born in / married in / died in jaffa.

Actual result:
Receive a messasge that says there are no results for Nikolai

Note:
The "No results" message should know how to "read" the filters used by the users.

**Comment by Netush** [comment]
Look st the sketch 
English:
https://projects.invisionapp.com/d/main#/console/904587/234817805/preview
Hebrew:
https://projects.invisionapp.com/d/main#/console/904587/234817806/preview

**Comment by OriHoch** [comment]
@TheGrandVizier @Netush please decide on the expected result
currently what's written in description doesn't match what's in the sketch

**Comment by OriHoch** [comment]
It seems to be it will be easiest to implement the pages to look like the sketch @Netush sent - as they don't contain reference to the actual search terms / filters

**Comment by nuritgazit** [comment]
I actually think we should do both:
provide the exact description of why we couldn't find results ("We found no results for Nikolai + Jaffa")
AND
Provide the general text that explains how to improve search results.

**Comment by Netush** [comment]
So this is the recent sketch: (Click to the left to see the English sketch) 
https://projects.invisionapp.com/d/main#/console/904587/123938613/preview

**Comment by Netush** [comment]
So the new sketch is approved. 
The image below should change any time the user get it - i'll publish in the near future a list of images.
below the image will be the title of the image with a link to the item page.
the text for the Hebrew & English is in the Invision at the Comment Mode also there is the text size
Same link as above:
https://projects.invisionapp.com/d/main#/console/904587/123938613/preview

**Comment by Netush** [comment]
Here is the list of Images
https://drive.google.com/drive/folders/0Bx1xuC3NtkTaU2hmSVR2ejhfZXc

**Comment by OriHoch** [comment]
@Netush @TheGrandVizier I understand issue was re-opened? please write a few words about the reason and what changes should be made

**Comment by TheGrandVizier** [comment]
Accidental close, thus reopened.
Nothing happened.

**Comment by OriHoch** [comment]
thanks @TheGrandVizier  - so what's the status of this issue?
I see it was completed and ready for QA - but before @Netush comments
if that's the case - I suggest to implement the new designs in a new issue

**Comment by TheGrandVizier** [comment]
Already done.

**Comment by OriHoch** [comment]
cool, thanks @TheGrandVizier could you link here to the new issue?

I'll delete @Netush comments with the new designs because they are confusing (to me..)

**Comment by OriHoch** [comment]
found the new issue - 
#410 
@Netush  - please review the new issue and ensure the spec and design is clear and correct..
