### ISSUE TITLE
Translate filter button for hebrew version

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#395]
Since we have all the other buttons translated it stands to reason this one is not different.

Reproduce:
1. use general search to find a person
2. Use general search family tree filters
3. Switch to Hebrew interface

Actual result:
Filter button is the only element on screen still in English.

Expected result:
All elements on the screen are now in hebrew.

**Comment by nuritgazit** [comment]
לדעתי "סינון"

**Comment by Netush** [comment]
זה סינון - אפשר לעיין גם בסקיצות
https://projects.invisionapp.com/d/main#/console/904587/218273109/preview

**Comment by OriHoch** [comment]
@TheGrandVizier why? it was fixed and merged
please write why it was reopened and what changes are needed

**Comment by TheGrandVizier** [comment]
I accidentally closed it, and thus reopened it. It was not meant to be closed.
