### ISSUE TITLE
Trees entered via General Search Results produce blank page, as their URL is broken.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#398]
Reproduce:
1. Use general search to search for the name Nikolai.
2. Go to people tab
3. Apply a filter. Place: moscow
4. Click on the result labeled "NIKOLAI (BERNSTEIN) ALEXANDROVITCH"

Expected Result:
1. User taken to tree at this URL:
http://test.dbs.bh.org.il/person/8888/0/I23775

Actual Result:
1. User taken to this URL:
http://test.dbs.bh.org.il/person/8888/0/

**Comment by nuritgazit** [comment]
@TheGrandVizier you pasted the same URL, I think

**Comment by TheGrandVizier** [comment]
Closing as duplicate.
