### ISSUE TITLE
Hebrew operators in person search should fit the box they are in

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#406]
The operators in hebrew do not fit the box they are in, causing overlap between the arrow and the word:
http://prntscr.com/fdpwuf

Repro:
1. Use general search
2. Go to persons tab
3. Switch to hebrew
4. change operator to "starts with" or "sounds like".

Expected result:
1. See an operator name and a dropdown arrow.

Actual result:
1. The operators are partially concealed.

**Comment by TheGrandVizier** [comment]
Not fixed:

**Comment by OriHoch** [comment]
@TheGrandVizier the fix was not merged yet
this issue is assigned to @Inna-r so she will merge the fix

**Comment by TheGrandVizier** [comment]
should not be marked as review / QA then ;)

**Comment by OriHoch** [comment]
ok.. will change to in progress, @Inna-r  - please merge, I approved the PR
