### ISSUE TITLE
We should only display one Family tree search / section / button

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#412]
Now that the family trees have been unified with General Search, there is no need for the old section and we can hide it or remove it. Personally I prefer we hide it, just in case we need to bring it back for some reason.

Repro:

1. Search for Cohen in general search
2. Click "Family Trees"

Expected result:
User finds tree button and arrives at Tree / Person filters and results.

Actual result:
User is confused by the presence of two buttons with the same meaning that do different things.

**Comment by Inna-r** [comment]
@TheGrandVizier , hidden, not yet deployed
