### ISSUE TITLE
Firefox should display the search operators and filters correctly.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#413]
The operators in hebrew, on firefox, do not fit the box they are in, causing overlap between the arrow and the word:
http://prntscr.com/fdpwuf

Repro:
1. Use general search
2. Go to persons tab
3. Switch to hebrew
4. change operator to "starts with" or "sounds like".

Expected result:
1. See an operator name and a dropdown arrow.

Actual result:
1. The operators are partially concealed.

**Comment by OriHoch** [comment]
@Inna-r I think it will be fixed in #407, please check

**Comment by OriHoch** [comment]
@TheGrandVizier please check if it's fixed, looking at the code seems like it should be fixed
