### ISSUE TITLE
Technical help to orgs who want their content to be part of our unified search

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#415]
We are in contact with different institutions who do not have internal developers / resources to develop an API, but still want to collaborate. They need our guidance / technical support / technical solution, in order to allow us to integrate their content on our unified search.

More details are here in this board: https://trello.com/b/nL3Wr7Ou/the-ring

**Comment by OriHoch** [comment]
Issue moved to [Beit-Hatfutsot/beit-hatfutsot-devops #26](https://github.com/Beit-Hatfutsot/beit-hatfutsot-devops/issues/26) via [**ZenHub**](https://www.zenhub.com/)
