### ISSUE TITLE
"Exit Tree" should lead back to your latest search results

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#419]
**Reproduce**

1. View a tree
2. Click "Exit tree".

**Expected Result:**
- Taken to the screen you viewed prior to entering the tree

**Actual Result:**
- Taken to http://test.dbs.bh.org.il/search which displays an empty UI.

**Comment by TheGrandVizier** [comment]
Bonus points if it can go back to the actual part of the result screen the user was last at (correct amount of "Show more").

**Comment by OriHoch** [comment]
I had a look at the code, it's not trivial to fix because we don't have the mechanism to do that (from what I could see)

**Comment by TheGrandVizier** [comment]
Note #1:
Currently the Exit Tree buttno does take a user back to the relevant results *if* the filters are used prior to entry to tree.

Note #2:
A user can enter a tree from his MJS. This needs to be accounted for in any fix.

**Comment by Netush** [comment]
Just for notice- there are 3 ways to exit a tree
1 from the general search results > All Results
2 From the general search results > People (Family Trees)
3 From "My Story"

**Comment by Libisch** [comment]
PR #423 merged.
