### ISSUE TITLE
Images and Videos "About" pages are empty

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#424]
Reproduce:
1. Navigate to the about page for videos:
http://test.dbs.bh.org.il/about/videos

Expected result:
1. Read information

Actual result:
1. Empty page

**Comment by Libisch** [comment]
@TheGrandVizier  Done, waiting for @OriHoch to approve PR #427.

**Comment by Libisch** [comment]
@TheGrandVizier Done.
