### ISSUE TITLE
Videos should be found when searched for

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#425]
Currently, we are not displaying any of the videos we have. The video section is empty.

Reproduce:
1. Arrive at general search
2. Search for "Benjamin"
3. Go to Video tab

Expected result:
1. Find videos labeled "Benjamin of Tudela".

Actual result:
1. No results found.

**Comment by Netush** [comment]
Also should appear at the "all results" tab (Depending on relevance)

**Comment by OriHoch** [comment]
fixed when moved to clearmash, looks like it works now
