### ISSUE TITLE
adjust general search and item page to the new data API format / schema

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#431]
### reproduction
* go to general search, get some search results
* go to an item (from any collection except family trees)

#### expected
* search results and item page are shown with data from the new pipelines
* not all details are displayed yet, but the basic data is shown
* see issues labeled `clearmash` for and idea of which details are still missing

### related issues
* https://github.com/Beit-Hatfutsot/dbs-back/issues/188
* [all clearmash related issues](https://github.com/issues?utf8=%E2%9C%93&q=repo%3Abeit-hatfutsot%2Fdbs-back+repo%3Abeit-hatfutsot%2Fdbs-front+repo%3Abeit-hatfutsot%2Fmojp-dbs-pipelines+repo%3Abeit-hatfutsot%2Fbeit-hatfutsot-devops+label%3Aclearmash)

**Comment by OriHoch** [comment]
### development status
[x] basic search (not all data is shown, but the basic functionality works)
[ ] item page

**Comment by OriHoch** [comment]
works on dev environment

**Comment by TheGrandVizier** [comment]
Indeed it does
