### ISSUE TITLE
place item page should show embedded google map

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#440]
### reproduction
* goto place which have coordinates (e.g. http://test.dbs.bh.org.il/place/moscow)

#### expected
* embedded map will be a google map with only the place (because that's what clearmash provides)
* need to change the title (because it's not "nearby places" anymore)
![image](https://user-images.githubusercontent.com/1198854/28112982-93fbf1a8-6703-11e7-86d5-431cbcae2ecf.png)

#### actual
no map

### notes
* clearmash provides url to google map, we can embed that directly
* it will be added to API in Beit-Hatfutsot/dbs-back#208

**Comment by Libisch** [comment]
@Netush @OriHoch 
The "Nearby Places" map is supposed to show the location of the place/item, alongside nearby places (in the example below, Berlin in marked by a red pin, and the others are blue). 

Either we change the title ("Nearby Places"), or the embedded map should be one that contains related places as well.

<img width="1214" alt="screen shot 2017-07-12 at 15 25 01" src="https://user-images.githubusercontent.com/20017334/28117547-860047f8-6716-11e7-818f-5f3edcfac5f8.png">

**Comment by OriHoch** [comment]
@Libisch deleted previous comment, moved to a new issue - #443

**Comment by OriHoch** [comment]
merged and deployed to dev (0.13.1)
