### ISSUE TITLE
wizard should work and fetch items from new ES

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#442]
### reproduction
* http://test.dbs.bh.org.il/
* type something in family name / place
* click start

#### expected
* should work

#### actual
* error
![image](https://user-images.githubusercontent.com/1198854/28115736-ca5d1a3c-670e-11e7-828a-f326dcf29365.png)

**Comment by OriHoch** [comment]
Issue moved to [Beit-Hatfutsot/dbs-back #209](https://github.com/Beit-Hatfutsot/dbs-back/issues/209) via [**ZenHub**](https://www.zenhub.com/)

**Comment by OriHoch** [comment]
backend was fixed, now need to make some adjustments in frontend

**Comment by OriHoch** [comment]
merged and deployed to dev (0.13.1)

**Comment by TheGrandVizier** [comment]
Tested, Verified, closing.
