### ISSUE TITLE
clearmash photoUnits with gallery should be shown as such

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#449]
### reproduction
* have a clearmash item with gallery
* e.g.: 
![image](https://user-images.githubusercontent.com/1198854/28864384-102cbd62-7775-11e7-8c51-53b092b46b9e.png)
* look for the item in the search results - [link](http://test.dbs.bh.org.il/he/%D7%97%D7%A4%D7%A9%D7%95?q=%D7%A8%D7%92%27%D7%99%D7%A0%D7%94%20%D7%95%D7%99%D7%A9%D7%95%D7%9C%D7%94%20%D7%91%D7%98%D7%99%D7%A0%D7%95%20%D7%91%D7%99%D7%95%D7%9D%20%D7%97%D7%AA%D7%95%D7%A0%D7%AA%D7%9D,%20%D7%98%D7%99%D7%A8%D7%A0%D7%94,%20%D7%90%D7%9C%D7%91%D7%A0%D7%99%D7%94,%201956&collection=images)
* look at the item page - [link](http://test.dbs.bh.org.il/he/%D7%A8%D7%92%D7%99%D7%A0%D7%94-%D7%95%D7%99%D7%A9%D7%95%D7%9C%D7%94-%D7%91%D7%98%D7%99%D7%A0%D7%95-%D7%91%D7%99%D7%95%D7%9D-%D7%97%D7%AA%D7%95%D7%A0%D7%AA%D7%9D-%D7%98%D7%99%D7%A8%D7%A0%D7%94-%D7%90%D7%9C%D7%91%D7%A0%D7%99%D7%94-1956/%D7%AA%D7%9E%D7%95%D7%A0%D7%94)

#### expected
* images gallery on item page

#### actual
* no images gallery

**Comment by OriHoch** [comment]
merged and deployed (need to wait for pipelines to sync image data)

**Comment by OriHoch** [comment]
pipelines data was synced

**Comment by TheGrandVizier** [comment]
Galleries work. Very nice.
