### ISSUE TITLE
ftree Notes field is limited and cannot contain entirety of some notes.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#45]
Some notes are very long.
The notes field in the ftree viewer is limited in size and cannot contain some of the lengthy notes left regarding some individuals in various tree.
Here is an example:

http://test.myjewishidentity.org/person/8888/I80530

**Comment by nuritgazit** [comment]
@daonb need to check if the db has the complete note. @Inna-r already checked that the API returns a truncated string.

**Comment by daonb** [comment]
It's a migration issue. The note field is truncated in the migration

**Comment by daonb** [comment]
Issue moved to [Beit-Hatfutsot/dbs-back #18](https://github.com/Beit-Hatfutsot/dbs-back/issues/18) via [**ZenHub**](https://www.zenhub.com/)
