### ISSUE TITLE
Migrate to HTTPS

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#459]
Starting October 2017, Chrome (version 62) will show a “NOT SECURE” warning when users enter text in a form on an HTTP page, and for all HTTP pages in Incognito mode. 

The following URLs on your site include text input fields (such as < input type="text" > or < input type="email" >) that will trigger the new Chrome warning.

[I'm sending the original message from Google via mail.]

The new warning is part of a long term plan to mark all pages served over HTTP as “not secure”. 

@Libisch is this something you can handle?

**Comment by OriHoch** [comment]
done
