### ISSUE TITLE
Ftrees features

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#46]
- [ ] research gedcom attachments

- [ ] notes - display full notes [example](http://test.dbs.bh.org.il/person/655/I2296)

- [ ] Support item attachment (UGC)

- [ ] add navigation hints

**Comment by nuritgazit** [comment]
@daonb Do you want to give this task to Adam?

**Comment by daonb** [comment]
I wish, but it has to do more with importing the GEDCOMs than the display so it has to be me.

**Comment by daonb** [comment]
Issue moved to [Beit-Hatfutsot/dbs-back #19](https://github.com/Beit-Hatfutsot/dbs-back/issues/19) via [**ZenHub**](https://www.zenhub.com/)
