### ISSUE TITLE
Explore our Open Databases tab should be link to main page

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#471]
In the new header, the tab of the DBs site should lead to its main page, as is the case in other 2 sites (when clicking the Museum tab in any of the internal pages of the museums site leads to main Museum page, same is for shop).

**Reproduction steps:**
* Go to any of the internal pages in the databases site, for example: https://dbs.bh.org.il/place/warszawa-warsaw 
* Click on "Explore our Open Databses" red tab in the header

**Expected result:**
* Cursor of mouse changes to indicate the tab is clickable
* Page changes to main page of the DBs site (https://dbs.bh.org.il/)

**Actual result:**
* Cursor of mouse changes to indicate the tab is clickable - so far so good
* nothing happens - user remains in the page he is in

**Comment by OriHoch** [comment]
done & deployed
