### ISSUE TITLE
Truncate long text in persons' names

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#49]
We have no truncation of very long persons names and [it looks bad](http://prntscr.com/b2botz).
If the name's area (width and height)  is too big for its container, we should

- get the first word
- if the first word's area is too big, remove the overflowed chars and replace with the three dots sign.

**Comment by TheGrandVizier** [comment]
@daonb

**Comment by nuritgazit** [comment]
@TheGrandVizier retest please

**Comment by TheGrandVizier** [comment]
No longer relevant
