### ISSUE TITLE
MJS: user can close login window but remain in MJS.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#51]
When a user navigates to MJS while logged off, the login window will appear.
However, the user may close the window and remain on this page.

The user should be taken back to where he was.
Alternatively, perhaps the login prompt should appear before the navigation takes place in the first place.

**Comment by TheGrandVizier** [comment]
Takes to home page instead of taking user to where he was before.
I still think there is no navigation needed until login takes place.

**Comment by Inna-r** [comment]
@TheGrandVizier please retest

**Comment by TheGrandVizier** [comment]
I dont see a difference in behavior from previous test @Inna-r
