### ISSUE TITLE
General search reverts to previous language once search initiated after language change.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#59]
Reproduce:
1. Clear Cache.
2. Navigate: test.myjewishidentity.org/he/
3. Search for "Cohen" and at the item page click "Search" to go to general search.
4. Search for Izmir.
5. Change language to english and search for Izmir again.

Result:
The Result page presented is in hebrew.

Note: changing tabs for search results also bounces the language back.

**Comment by Inna-r** [comment]
@TheGrandVizier please retest
