### ISSUE TITLE
"Remove from my story" inside MJS (cardS) does not remove the item until page is refreshed.

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-front#6]
When removing an item from the story using it's MJS card, the card is not removed from the story until the page is refreshed.

Repro:
1. Add Item to story.
2. Got to MJS.
3. Expand the options for the item in MJS.
4. Remove the item from your story.
Result:
The item is still there.
Note: Refreshing the page will remove the item.

**Comment by TheGrandVizier** [comment]
Not fixed
