### ISSUE TITLE
Cant display death if no birth/death dates + bonus

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#74]
We cannot determine life or death of entrants with no date entries at all.
This is particularly visible when there is an entire tree of dead people and the topmost ancestor is marked as alive.

One suggestion is to Assume that IF all children are dead, it safe to say the person himself is also dead.
@nuritgazit  input please

**Comment by nuritgazit** [comment]
This looks like a decent solution

**Comment by daonb** [comment]
I thought we no longer mark people as dead or alive

**Comment by TheGrandVizier** [comment]
This is true. Closing issue.
