### ISSUE TITLE
Sometimes, last names are no longer shown in trees.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#75]
Same tree:

http://prntscr.com/9xzkjj Has Last name
http://prntscr.com/9xzkoz Has no last name

Only difference is that it was tempered with, clicked on, dragged around.
Still investigating.

**Comment by nuritgazit** [comment]
@TheGrandVizier retest!!

**Comment by TheGrandVizier** [comment]
Cannot reproduce, treating as fixed.
