### ISSUE TITLE
The system attempts to show Image items that have no virtual representation.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#77]
Images that exist in BHP but have not been scanned still are registered as images.
As such, we attempt to present them as part of collections and possibly single image item pages as well.

These image entries can in fact be Slides, Slideshows, Paintings and photos that simply were never scanned. They exist in the real world and are stored in the museum, but have no virtual representation.

Example:
http://test.myjewishidentity.org/item/photoUnits/39767
In this collection, the first and second image two different types of slides that were never scanned.
The third image is a regular image that was scanned and thus shows up correctly.

**Comment by daonb** [comment]
@TheGrandVizier we need a correct url

**Comment by nuritgazit** [comment]
@TheGrandVizier are we talking about this case: http://dbs.bh.org.il/image/view-of-the-joden-savanne-surinam-water-color-1839 ?

**Comment by daonb** [comment]
For now, we should hide all traces of images that are not available.
Heere's another [example](http://dbs.bh.org.il/image/jewish-boy-scouts-members-holding-jnf-boxes-tripoli-libya-1946).

**Comment by TheGrandVizier** [comment]
This means that some collections will now be collections of one image.
Is there an expected behavior for this type of items?

**Comment by daonb** [comment]
For now, it's just a collection with one image. Maybe we should open an `enhancement` issue for doing this better.

**Comment by nuritgazit** [comment]
No, we have talked about this in the past, and created a stab. The design is here: https://www.dropbox.com/work/DBs/db_design/DBs%20Design/Error?preview=ItemPage-Eror_Eror-Digition-1-heb.jpg

**Comment by daonb** [comment]
I can't get into Dropbox. Can someone please  get the image and add it to the description of this issue?

**Comment by TheGrandVizier** [comment]
cant get in either. demands business account.

**Comment by Netush** [comment]
![digitization-heb](https://cloud.githubusercontent.com/assets/19781656/18814073/c9eeb08c-8317-11e6-9990-724c4dfd59e0.jpg)
![digitization-eng](https://cloud.githubusercontent.com/assets/19781656/18814072/c9edb86c-8317-11e6-8587-bd9d4f82ed24.jpg)

**Comment by daonb** [comment]
IMO, when we have two photos and only one of them is available, start with it.

**Comment by nuritgazit** [comment]
I agree, but it shouldn't be this solution or that - it should be both

**Comment by daonb** [comment]
right.
@Inna-r please close this issue and open a new enhancement issue with a full description.

**Comment by TheGrandVizier** [comment]
Two adjustments requested:

1. "Image not yet digitized" -> "Image is not yet digitize"
2. Change "click here" to "Click on this image..."

**Comment by Netush** [comment]
Sent you the revised images a week ago

**Comment by Inna-r** [comment]
@Netush thanks!
