### ISSUE TITLE
Sometimes item are related to themselves.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#78]
Several cases were found where related values returned the page itself as related.

Examples:

1. http://test.myjewishidentity.org/item/personalities/156600 (http://i.imgur.com/IgMXeVX.png)

**Comment by daonb** [comment]
The new link is -  http://test.dbs.bh.org.il/personality/cohen-ronald - and it seems like it's solved.
