### ISSUE TITLE
General Search Results page has no appropriate name for the browser's tab.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#79]
Browser tabs are named accordingly for most pages. Item pages are named 
"NAME | BHS"
Home page:
"Home Page | BHS"

The general search results page is just "BHS".

**Comment by TheGrandVizier** [comment]
@nuritgazit 
Some one needs to decide what the label of the search results page should be.
Currently it inherits the name of the last seen item page.

**Comment by nuritgazit** [comment]
Is there character limit on the labels?

**Comment by nuritgazit** [comment]
@TheGrandVizier @daonb Is there a character limit?

**Comment by nuritgazit** [comment]
Home | BH Open Databases
Results | BH Open Databases
My Story | BH Open Databases
Family Trees | Open Databases
Hebrew:
(further consultation with SEO guys is required)
