### ISSUE TITLE
Family tree tab in search results remains highlighted once it is selected for the first time

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#86]
The Family Trees tab remains hihglighted forever once it is selected.
Causes bad indications on tab navigation.

See screenshot:
http://prntscr.com/9chvz5

**Comment by daonb** [comment]
IMHO, that's the design. @Netush , right?

**Comment by Netush** [comment]
Remember the allegory about the shit barrel, well this is our navigation bar it not one drop of shit but a couple (:

The family trees tab will remain open at the same time with the recently view tab or the general search tab, and remain like this until the user leave the family trees. The same behavior will be at "my story page and now that we adding back all the tabs to the home page, it will the same also at the home page.

**Comment by TheGrandVizier** [comment]
Yes. The point is that only one element should be highlighted at a time.

**Comment by Netush** [comment]
Agreed, but for now that's what we have.
