### ISSUE TITLE
Links - case where Place does not link to another Place.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#88]
This page:
http://test.myjewishidentity.org/item/places/72125
contains the word "Fez", which is a place we have an item page for.
All rules for links are followed.
1. Source is a place page.
2. Target is a place page.
3. Word is not misspelled.
4. http://test.myjewishidentity.org/item/places/72307 is the target page.

No link generated.
Suspect cap-sensitivity, as the target page is titled FEZ

**Comment by daonb** [comment]
The links are outdated

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/bds-back#1
