### ISSUE TITLE
Videos: Fast navigation causes videos to play after user left the page.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#94]
FF/IE

If a user navigates quickly between some pages and one of them is a Video page, a video may start playing after the user has already left it's page. The user will not be able to stop it without refreshing or closing the tab.

Repro:
1. Navigate to http://test.myjewishidentity.org/item/movies/111522
2. Navigate to a couple of related items and back, rather fast.

Result: A video will play without the user being on it's page, unable to stop it.

**Comment by daonb** [comment]
@TheGrandVizier we need a new link
