### ISSUE TITLE
Add `grunt serve` command

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-front#99]
Currently, our README ends with `grunt build` which creates a public directory, but doesn't server the files.  We leave it to the user to set up a local file server and use it to see the site.

Would be nice to have a `grunt serve` command that will build and serve the files and update whenever the source changes.

**Comment by daonb** [comment]
@alonisser can you help?

**Comment by alonisser** [comment]
yap, It might be a while , but quite easy to setup

**Comment by daonb** [comment]
Meir started working on gulp transition #122 so this is no longer valid
